import { Hono } from "npm:hono";
import { cors } from "npm:hono/cors";
import { logger } from "npm:hono/logger";
import * as kv from "./kv_store.tsx";
import { personas } from "./personas.tsx";
import { organizaciones } from "./organizaciones.tsx";
import { roles } from "./roles.tsx";
import { pedidos } from "./pedidos.tsx";
import { metodosPago } from "./metodos_pago.tsx";
import { metodosEnvio } from "./metodos_envio.tsx";
import { etiquetas } from "./etiquetas.tsx";
import { roadmap } from "./roadmap.tsx";
import { ideasBoard } from "./ideas_board.tsx";
import { cargaMasiva } from "./carga_masiva.tsx";
import { ageVerification } from "./age_verification.tsx";
import { rrss } from "./rrss.tsx";
import { marketing } from "./marketing.tsx";
import { productos } from "./productos.tsx";
import { carrito } from "./carrito.tsx";
import { departamentos } from "./departamentos.tsx";
import { ordenes } from "./ordenes.tsx";
import { categorias } from "./categorias.tsx";
import { subcategorias } from "./subcategorias.tsx";
import { disputas } from "./disputas.tsx";
import { fulfillment } from "./fulfillment.tsx";
import { produccion } from "./produccion.tsx";
import { abastecimiento } from "./abastecimiento.tsx";
import { mapaEnvios } from "./mapa-envios.tsx";
import { transportistas } from "./transportistas.tsx";
// Hub Logistico — Paso 7
import { envios } from "./envios.tsx";
import { rutas } from "./rutas.tsx";
import { vehiculos } from "./vehiculos.tsx";
import { depositos } from "./depositos.tsx";
import { inventario } from "./inventario.tsx";
import { entregas } from "./entregas.tsx";
import { tracking } from "./tracking.tsx";

const app = new Hono().basePath("/api");
app.use("/*", logger());

app.route("/kv", kv.kv);
app.route("/personas", personas);
app.route("/organizaciones", organizaciones);
app.route("/roles", roles);
app.route("/pedidos", pedidos);
app.route("/metodos-pago", metodosPago);
app.route("/metodos-envio", metodosEnvio);
app.route("/etiquetas", etiquetas);
app.route("/roadmap", roadmap);
app.route("/ideas-board", ideasBoard);
app.route("/carga-masiva", cargaMasiva);
app.route("/age-verification", ageVerification);
app.route("/rrss", rrss);
app.route("/marketing", marketing);
app.route("/productos", productos);
app.route("/carrito", carrito);
app.route("/departamentos", departamentos);
app.route("/ordenes", ordenes);
app.route("/categorias", categorias);
app.route("/subcategorias", subcategorias);
app.route("/disputas", disputas);
app.route("/fulfillment", fulfillment);
app.route("/produccion", produccion);
app.route("/abastecimiento", abastecimiento);
app.route("/mapa-envios", mapaEnvios);
app.route("/transportistas", transportistas);
// Hub Logistico
app.route("/envios", envios);
app.route("/rutas", rutas);
app.route("/vehiculos", vehiculos);
app.route("/depositos", depositos);
app.route("/inventario", inventario);
app.route("/entregas", entregas);
app.route("/tracking", tracking);

Deno.serve(app.fetch);
